name: Frontend CI Pipeline

on:
  pull_request:
    push:
      branches: 
        - main

jobs:
    test-and-build:
      runs-on: ubuntu-latest
      name: Test-and-Build
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '23'

        - name: Install Dependencies
          run: npm install

        - name: Run ESLint
          run: npm run lint

        - name: Run Tests
          run: npm run test -- --coverage

        - name: Build 
          run: npm run build